### ISSUE TITLE
update gpg4win to latest version

### ISSUE THREAD

**Issue by mfc** [glamrock/Satori#4]
gpg4win 2.2.5 was released 2015-07-10, includes lots of important updates:
http://gpg4win.org/change-history.html

given that gpg4win is the only secure communications tool provided by Satori that does not have a valid TLS download option for users, non-technical end-users are very reliant on Satori to download & check its integrity.

**Comment by glamrock** [comment]
Hey!
Sorry I didn't notice this bug until now, but gpg4win was updated some time ago. Thanks!

**Comment by mfc** [comment]
yep, you're right! all up-to-date, sweet. can be clooooosed
