### ISSUE TITLE
use consistent language re: checksum vs hash

### ISSUE THREAD

**Issue by mfc** [glamrock/Satori#5]
next to tools, the "checksum" can be displayed. At the bottom of the Satori window it says "Generate Hash". 

For the end-user, they are supposed to know that they are comparing the "checksum" to the "hash". 

This could be communicated more clearly if only one synonym was used, either "checksum" for both (so "Generate checksum" at the bottom) or "hash" for both. 

I would lean towards "checksum" since "hash" may already have meanings in the user's mind.

**Comment by glamrock** [comment]
Merged; closing.
